### ISSUE TITLE
The .exe file in release mode is as big as in debug mode

### ISSUE THREAD

**Issue by AphaseDev** [asmaloney/asmCrashReport#1]
HI,

Thank you for your simple and powerfull crash report tool!
It works on my project with MinGW32. 
The only thing I noticed is that after importing the asmCrashReport, my exe file in release mode has increased a lot! (same size as in debug mode).
Is it due to a compiler setting or something ? 

Thanks for your help.

**Comment by asmaloney** [comment]
Yes - if you look in the .pri, you'll see that I've added " -g" to the release c++ flags and removed optimization:

```
QMAKE_CFLAGS_RELEASE += -g -O0
QMAKE_CXXFLAGS_RELEASE += -g -O0
```

In order to provide a usable stacktrace to show where the crash occurred, it needs to include the compiler symbols. The extra symbols won't impact your code - they just take up space.

The way I use this is to keep a version of my software with asmCrashReport compiled in it to send to customers who are having reproducible issues on their end that I cannot reproduce on my end.

Other schools of thought would have you just use "-g -O2" which gives you a release version with debug symbols - and just ship it. It will be larger (as you point out) though. In this case you have to take care when reading the stacktrace because the references to line numbers and so on might be incorrect due to optimization.

If you want to do this, then I think you can change the section in the .pri to:
```
win32-g++* {
        QMAKE_CFLAGS_RELEASE += -g
        QMAKE_CXXFLAGS_RELEASE += -g
        QMAKE_LFLAGS_RELEASE =

        LIBS += "-L$$PWD/Win/WinDebug" -lDbghelp
}
```

**Comment by AphaseDev** [comment]
Hi,

Thank you for your detailed answer!
As of now, I made a version of my software with asmCrashReport just like you in order to evaluate it.

**Comment by asmaloney** [comment]
Great - good luck and happy (!) crash debugging.
